# Generated by Django 4.1 on 2023-01-24 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_socialmediasettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialMediaSettings',
        ),
    ]
