# Generated by Django 4.1 on 2023-05-03 17:14

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_contactpage_signuppage'),
    ]

    operations = [
        migrations.AddField(
            model_name='releasespage',
            name='releases',
            field=wagtail.fields.StreamField([('releases', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('link', wagtail.blocks.URLBlock(required=True))]))], null=True, use_json_field=None),
        ),
    ]
