# Generated by Django 4.1 on 2023-05-04 07:10

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_releasespage_releases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='releasespage',
            name='releases',
        ),
        migrations.AddField(
            model_name='releasespage',
            name='catalogue',
            field=wagtail.fields.StreamField([('catalogue', wagtail.blocks.StructBlock([('releases', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('link', wagtail.blocks.URLBlock(required=True)), ('artist', wagtail.blocks.CharBlock(required=True)), ('title', wagtail.blocks.CharBlock(required=True)), ('type', wagtail.blocks.CharBlock(required=False))])))]))], null=True, use_json_field=True),
        ),
    ]
