# Generated by Django 4.1 on 2023-05-08 17:37

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_releasespage_releases_releasespage_catalogue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='releasespage',
            name='catalogue',
        ),
        migrations.AddField(
            model_name='merchpage',
            name='merchcat',
            field=wagtail.fields.StreamField([('merchcat', wagtail.blocks.StructBlock([('merch', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('link', wagtail.blocks.URLBlock(required=True)), ('description', wagtail.blocks.CharBlock(required=True)), ('type', wagtail.blocks.CharBlock(required=False)), ('price', wagtail.blocks.CharBlock(required=False))])))]))], null=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='releasespage',
            name='releasecat',
            field=wagtail.fields.StreamField([('releasecat', wagtail.blocks.StructBlock([('releases', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('link', wagtail.blocks.URLBlock(required=True)), ('artist', wagtail.blocks.CharBlock(required=True)), ('title', wagtail.blocks.CharBlock(required=True)), ('type', wagtail.blocks.CharBlock(required=False))])))]))], null=True, use_json_field=True),
        ),
    ]
