# Generated by Django 4.1 on 2023-05-08 17:55

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_releasespage_catalogue_merchpage_merchcat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='releasespage',
            name='releasecat',
        ),
        migrations.AddField(
            model_name='releasespage',
            name='releases_catalogue',
            field=wagtail.fields.StreamField([('releases_catalogue', wagtail.blocks.StructBlock([('releases', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('link', wagtail.blocks.URLBlock(required=True)), ('artist', wagtail.blocks.CharBlock(required=True)), ('title', wagtail.blocks.CharBlock(required=True)), ('type', wagtail.blocks.CharBlock(required=False))])))]))], null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='merchpage',
            name='merchcat',
            field=wagtail.fields.StreamField([('merchcat', wagtail.blocks.StructBlock([('merch', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('link', wagtail.blocks.URLBlock(required=True)), ('description', wagtail.blocks.CharBlock(required=True)), ('type', wagtail.blocks.CharBlock(required=True)), ('price', wagtail.blocks.CharBlock(required=True))])))]))], null=True, use_json_field=True),
        ),
    ]
