# Generated by Django 4.1 on 2023-05-13 15:27

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_aboutpage_gaming_info_aboutpage_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signuppage',
            name='signup_text',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
