# Generated by Django 4.1 on 2023-05-14 17:16

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_signuppage_signup_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='latest_releases',
            field=wagtail.fields.StreamField([('latest_releases', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(default='Latest Releases', required=False))]))], null=True, use_json_field=True),
        ),
    ]
