# Generated by Django 4.1 on 2023-05-14 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_homepage_latest_releases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
    ]
