# Generated by Django 4.1 on 2023-05-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='live',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='release',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
