# Generated by Django 4.1 on 2023-05-17 08:57

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_artistpage_photo_artistpage_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('latest_releases', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(default='Latest Releases', required=False)), ('limit', wagtail.blocks.IntegerBlock(default=3, label='Show maximum', required=True))])), ('artists', wagtail.blocks.StructBlock([('artists', wagtail.blocks.ListBlock(wagtail.blocks.PageChooserBlock('home.ArtistPage', required=True), required=True))]))], null=True, use_json_field=True),
        ),
    ]
