# Generated by Django 4.1 on 2023-05-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_release_url_alter_homepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='release_type',
            field=models.CharField(choices=[('Single', 'Single'), ('EP', 'EP'), ('Album', 'Album'), ('Compilation', 'Compilation')], default='Single', max_length=11, null=True),
        ),
    ]
