# Generated by Django 4.1 on 2023-05-21 14:43

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_release_release_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistpage',
            name='bio',
            field=wagtail.fields.RichTextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='gaming_info',
            field=wagtail.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='history',
            field=wagtail.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='mission_statement',
            field=wagtail.fields.RichTextField(),
        ),
    ]
