# Generated by Django 4.1 on 2023-05-21 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('home', '0031_rosterpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='photo_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.image'),
        ),
    ]
