# Generated by Django 4.1 on 2023-05-21 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_merchitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MerchItem',
        ),
    ]
