# Generated by Django 4.1 on 2023-06-02 12:44

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('home', '0038_alter_homepage_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(null=True)),
                ('description', models.CharField(max_length=455)),
                ('live', models.BooleanField(blank=True, default=False)),
                ('artist_pages', modelcluster.fields.ParentalManyToManyField(blank=True, related_name='+', to='home.artistpage')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
