# Generated by Django 4.1 on 2023-06-02 12:57

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_newsitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='description',
            field=wagtail.fields.RichTextField(),
        ),
    ]
