# Generated by Django 4.1 on 2023-06-04 15:05

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_alter_homepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistpage',
            name='body',
            field=wagtail.fields.StreamField([('latest_releases', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(default='Latest Releases', required=False)), ('limit', wagtail.blocks.IntegerBlock(default=3, label='Show maximum', required=True))])), ('latest_merch', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(default='Latest Merch', required=False)), ('limit', wagtail.blocks.IntegerBlock(default=3, label='Show maximum', required=True))])), ('news', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(default='Latest News', required=False)), ('limit', wagtail.blocks.IntegerBlock(default=2, label='Show maximum', required=True))]))], null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='artistpage',
            name='bio',
            field=wagtail.fields.RichTextField(blank=True, max_length=800, null=True),
        ),
    ]
