# Generated by Django 4.1 on 2023-06-04 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_artistpage_body_alter_artistpage_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistpage',
            name='body',
        ),
    ]
