# Generated by Django 4.1 on 2023-06-04 15:53

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_remove_artistpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchpage',
            name='merch_catalogue',
            field=wagtail.fields.StreamField([('merch_catalogue', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(default='Latest Merch', required=False)), ('limit', wagtail.blocks.IntegerBlock(default=3, label='Show maximum', required=True))]))], null=True, use_json_field=True),
        ),
    ]
