# Generated by Django 4.1 on 2023-06-04 16:07

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_alter_merchpage_merch_catalogue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('latest_releases', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(default='Latest Releases', required=False)), ('limit', wagtail.blocks.IntegerBlock(default=3, label='Show maximum', required=True))])), ('artists', wagtail.blocks.StructBlock([('artists', wagtail.blocks.ListBlock(wagtail.blocks.PageChooserBlock('home.ArtistPage', required=True), required=True))])), ('latest_merch', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(default='Latest Merch', required=False)), ('limit', wagtail.blocks.IntegerBlock(default=3, label='Show maximum', required=True))])), ('news', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(default='Latest Merch', required=False)), ('limit', wagtail.blocks.IntegerBlock(default=2, label='Show maximum', required=True))]))], null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='merchpage',
            name='merch_catalogue',
            field=wagtail.fields.StreamField([('merch_catalogue', wagtail.blocks.StructBlock([('merch', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('link', wagtail.blocks.URLBlock(required=True)), ('description', wagtail.blocks.CharBlock(required=True)), ('type', wagtail.blocks.CharBlock(required=True)), ('price', wagtail.blocks.CharBlock(required=True))])))]))], null=True, use_json_field=True),
        ),
    ]
