# Generated by Django 4.1 on 2023-06-04 19:37

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_alter_homepage_body_alter_merchpage_merch_catalogue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('embed', models.URLField(null=True)),
                ('description', wagtail.fields.RichTextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
