# Generated by Django 4.1 on 2023-06-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='live',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
