# Generated by Django 4.1 on 2023-06-04 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_playlist_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='headline',
            field=models.CharField(default='for the something', max_length=255),
            preserve_default=False,
        ),
    ]
