# Generated by Django 4.1 on 2023-06-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0053_rename_embed_playlist_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
