# Generated by Django 4.1 on 2023-06-07 18:38

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0054_playlist_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistpage',
            name='body',
            field=wagtail.fields.StreamField([('playlists', wagtail.blocks.StructBlock([('objects', wagtail.blocks.ListBlock(wagtail.snippets.blocks.SnippetChooserBlock('home.Playlist', required=True), required=True))]))], null=True, use_json_field=True),
        ),
    ]
