# Generated by Django 4.1 on 2023-06-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0055_playlistpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistpage',
            name='songkick_url',
            field=models.URLField(null=True),
        ),
    ]
