# Generated by Django 4.1 on 2023-06-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0056_artistpage_songkick_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistpage',
            name='songkick_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
