# Generated by Django 4.1 on 2023-06-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0057_alter_artistpage_songkick_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistpage',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
    ]
