# Generated by Django 4.1 on 2023-06-17 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0058_artistpage_instagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistpage',
            name='playlist',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artistpage',
            name='spotify',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artistpage',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
