# Generated by Django 4.1 on 2023-06-18 13:06

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0059_artistpage_playlist_artistpage_spotify_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='artist_pages',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='+', to='home.artistpage'),
        ),
    ]
