# Generated by Django 4.1 on 2023-06-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0060_playlist_artist_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistpage',
            name='social_feed',
            field=models.URLField(blank=True, null=True),
        ),
    ]
