# Generated by Django 4.1 on 2023-06-18 15:34

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0061_artistpage_social_feed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistpage',
            name='social_feed',
            field=wagtail.fields.RichTextField(blank=True, max_length=800, null=True),
        ),
    ]
