# Generated by Django 4.1 on 2023-06-18 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0063_alter_artistpage_social_feed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistpage',
            name='social_feed',
        ),
    ]
