# Generated by Django 4.1 on 2023-06-21 17:28

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0065_artistpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistpage',
            name='body',
            field=wagtail.fields.StreamField([('releases', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(default='Releases', required=False)), ('limit', wagtail.blocks.IntegerBlock(default=3, label='Show maximum', required=True))])), ('latest_merch', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(default='Latest Merch', required=False)), ('limit', wagtail.blocks.IntegerBlock(default=3, label='Show maximum', required=True))])), ('news', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(default='Latest Merch', required=False)), ('limit', wagtail.blocks.IntegerBlock(default=2, label='Show maximum', required=True))])), ('playlist', wagtail.blocks.StructBlock([('objects', wagtail.blocks.ListBlock(wagtail.snippets.blocks.SnippetChooserBlock('home.Playlist', required=True), required=True))]))], null=True, use_json_field=True),
        ),
    ]
