# Generated by Django 4.1 on 2023-06-21 18:49

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0066_alter_artistpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistpage',
            name='body',
            field=wagtail.fields.StreamField([('releases', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(default='Releases', required=False)), ('limit', wagtail.blocks.IntegerBlock(default=3, label='Show maximum', required=True))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
