# Generated by Django 4.2.2 on 2023-08-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0069_alter_homepage_body_alter_merchpage_merch_catalogue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistpage',
            name='rss_feed',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
