# Generated by Django 4.2.2 on 2023-08-15 15:19

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0070_artistpage_rss_feed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releasespage',
            name='releases_catalogue',
            field=wagtail.fields.StreamField([('releases_catalogue', wagtail.blocks.StructBlock([('releases', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('link', wagtail.blocks.URLBlock(required=True)), ('artist', wagtail.blocks.CharBlock(required=True)), ('title', wagtail.blocks.CharBlock(required=True)), ('type', wagtail.blocks.CharBlock(required=False))])))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
