# Generated by Django 4.2.2 on 2023-08-21 17:22

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0071_alter_releasespage_releases_catalogue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchpage',
            name='merch_catalogue',
        ),
        migrations.RemoveField(
            model_name='releasespage',
            name='releases_catalogue',
        ),
        migrations.RemoveField(
            model_name='rosterpage',
            name='body',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('latest_releases', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(default='Latest Releases', required=False)), ('limit', wagtail.blocks.IntegerBlock(default=3, label='Show maximum', required=True))])), ('artists', wagtail.blocks.StructBlock([('artists', wagtail.blocks.ListBlock(wagtail.blocks.PageChooserBlock('home.ArtistPage', required=True), required=True))])), ('latest_merch', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(default='Latest Merch', required=False)), ('limit', wagtail.blocks.IntegerBlock(default=3, label='Show maximum', required=True))])), ('news', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(default='Latest News', required=False)), ('limit', wagtail.blocks.IntegerBlock(default=2, label='Show maximum', required=True))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
