# Generated by Django 4.2.2 on 2023-08-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0072_remove_merchpage_merch_catalogue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecarouselimages',
            name='text',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='homepagecarouselimages',
            name='type',
            field=models.CharField(blank=True, choices=[('Release', 'Release'), ('Merch', 'Merch'), ('Playlist', 'Playlist'), ('News', 'News')], default='News', max_length=11, null=True),
        ),
    ]
