# Generated by Django 4.2.2 on 2023-08-30 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0073_homepagecarouselimages_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecarouselimages',
            name='text',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
