# Generated by Django 4.2.2 on 2023-09-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0074_alter_homepagecarouselimages_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecarouselimages',
            name='text',
            field=models.CharField(default='', max_length=255),
        ),
    ]
