# Generated by Django 4.2.2 on 2023-09-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0075_alter_homepagecarouselimages_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistpage',
            name='apple_music',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artistpage',
            name='tiktok',
            field=models.URLField(blank=True, null=True),
        ),
    ]
