# Generated by Django 4.2.2 on 2023-09-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0076_artistpage_apple_music_artistpage_tiktok'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='release_label',
            field=models.CharField(choices=[('Single', 'Single'), ('EP', 'EP'), ('Album', 'Album'), ('Compilation', 'Compilation')], default='Circus Records', max_length=11, null=True),
        ),
    ]
