# Generated by Django 4.2.2 on 2023-09-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0077_release_release_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='release_label',
            field=models.CharField(choices=[('Circus Records', 'Circus Records'), ('Circus Electric', 'Circus Electric')], default='Circus Records', max_length=15, null=True),
        ),
    ]
