# Generated by Django 4.2.2 on 2023-09-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0078_alter_release_release_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='release_type',
            field=models.CharField(choices=[('Single', 'Single'), ('EP', 'EP'), ('Album', 'Album'), ('Compilation', 'Compilation')], default='Single', max_length=15, null=True),
        ),
    ]
