# Generated by Django 4.2.2 on 2023-09-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0079_alter_release_release_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecarouselimages',
            name='type',
            field=models.CharField(blank=True, choices=[('Release', 'Release'), ('Merch', 'Merch'), ('Playlist', 'Playlist'), ('News', 'News')], default='News', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='merchitem',
            name='merch_type',
            field=models.CharField(blank=True, choices=[('T-shirt', 'T-shirt'), ('Hoodie', 'Hoodie'), ('Hat', 'Hat'), ('Vinyl', 'Vinyl')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='release',
            name='release_label',
            field=models.CharField(choices=[('Circus Records', 'Circus Records'), ('Circus Electric', 'Circus Electric')], default='Circus Records', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='release',
            name='release_type',
            field=models.CharField(choices=[('Single', 'Single'), ('EP', 'EP'), ('Album', 'Album'), ('Compilation', 'Compilation')], default='Single', max_length=255, null=True),
        ),
    ]
