# Generated by Django 4.2.2 on 2023-09-17 15:49

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0080_alter_homepagecarouselimages_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='description',
            field=wagtail.fields.RichTextField(max_length=255),
        ),
    ]
