# Generated by Django 4.2.2 on 2025-04-02 12:51

from django.db import migrations, models
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0083_privacypolicy_termsconditions'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.CharField(max_length=255)),
                ('date', models.DateField(null=True)),
                ('artist_pages', modelcluster.fields.ParentalManyToManyField(related_name='+', to='home.artistpage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
