# Generated by Django 4.2.2 on 2025-04-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0084_livedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='livedate',
            name='ticket_link',
            field=models.URLField(null=True),
        ),
    ]
