# Generated by Django 4.2.2 on 2025-04-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0085_livedate_ticket_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='livedate',
            name='event_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
