# Generated by Django 4.2.2 on 2025-04-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0086_livedate_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='livedate',
            name='live',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
