# Generated by Django 5.2.13 on 2026-04-21 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0087_livedate_live'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistpage',
            name='photo',
        ),
    ]
