# Generated by Django 5.2.13 on 2026-04-22 15:36

import django.utils.timezone
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0088_remove_artistpage_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='sort_order',
        ),
        migrations.AddField(
            model_name='livedate',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='merchitem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='playlist',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='release',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='livedate',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livedate',
            name='ticket_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='merchitem',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='description',
            field=wagtail.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='release',
            name='release_label',
            field=models.CharField(choices=[('Circus Records', 'Circus Records'), ('Circus Electric', 'Circus Electric')], default='Circus Records', max_length=255),
        ),
        migrations.AlterField(
            model_name='release',
            name='release_type',
            field=models.CharField(choices=[('Single', 'Single'), ('EP', 'EP'), ('Album', 'Album'), ('Compilation', 'Compilation')], default='Single', max_length=255),
        ),
        migrations.AlterField(
            model_name='release',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
